BDD test branch
BME-MIT-IET/iet-hf2021-sparba-qlene-sietni pull request #14
Opened 2021-05-04 18:44 UTC by benoero99

Ez az ág szolgál a BDD tesztek készítésére.

2021-05-04 18:44 UTC, benoero99 commented
Létrehoztuk a tesztkörnyezetet. Kezdetben a program Query részével foglalkoztunk. Írtunk 2 kisebb és egy nagyobb tesztet, ezáltal 7,5%-os lefedettséget elérve. A tesztek sikeresen lefutottak. A tesztek írása előtt és közben is folyamatosan tanulmányoztuk a programot.

2021-05-04 19:37 UTC, P6Z3F2 reviewed
Jók a tesztek, a lefedettséget ha lehet növeljétek, csak így tovább!

2021-05-05 08:32 UTC, P6Z3F2 commented on BDDTest/Steps/FilterSteps.cs
> +        RDFResource age = new RDFResource(RDFVocabulary.RDF.BASE_URI + "age");
Azok a mezők amiknek csak a konstruktorban adunk értéket, azoknak readonly-nak kéne lenniük.

2021-05-05 08:35 UTC, P6Z3F2 commented on BDDTest/Steps/FilterSteps.cs
> +            RDFResource person = new RDFResource(RDFVocabulary.RDF.BASE_URI + "person");
Nem szerencsés ugyanazt a változónevet adni, mint ami létezik a függvényen kívül, nevezzétek át az egyiket.

2021-05-05 08:35 UTC, P6Z3F2 commented on BDDTest/Steps/FilterSteps.cs
> +            RDFTypedLiteral ageLiteral = new RDFTypedLiteral("old", RDFModelEnums.RDFDatatypes.XSD_STRING);
Itt ugyanez.

2021-05-05 08:36 UTC, P6Z3F2 requested changes
Kérlek javítsátok ki a kommentjeimnél jelzett code smelleket.

2021-05-05 13:18 UTC, benoero99 commented on BDDTest/Steps/FilterSteps.cs
> +        RDFResource age = new RDFResource(RDFVocabulary.RDF.BASE_URI + "age");
Javítva!

2021-05-05 13:18 UTC, benoero99 commented on BDDTest/Steps/FilterSteps.cs
> +            RDFResource person = new RDFResource(RDFVocabulary.RDF.BASE_URI + "person");
Javítva!

2021-05-05 13:18 UTC, benoero99 commented on BDDTest/Steps/FilterSteps.cs
> +            RDFTypedLiteral ageLiteral = new RDFTypedLiteral("old", RDFModelEnums.RDFDatatypes.XSD_STRING);
Javítva!

2021-05-05 14:30 UTC, P6Z3F2 approved these changes
Szépen ki lettek javítva a CodeSmellek és a tesztek is rendben vannak! Részemről mergelhettek, de ha gondoljátok csinálhattok még tesztet.

2021-05-05 18:45 UTC, merged

2021-05-05 18:56 UTC, benoero99 commented
Fix #13